on:
  push:
    - Producao

name: Deploy MaueOrder
jobs:
  web-deploy:
    name: Deploy MaueOrder
    runs-on: ubuntu-latest
    steps:
    - name: Pegar codigo
      uses: actions/checkout@v2

    - name: Sincronizar Pastas
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_dir }}